#pragma once
#include <Windows.h>
#include <filesystem>
#include <iostream>
#include <sstream>
#include <string>
#include <regex>
#include <conio.h>
#include <ShObjIdl.h>
#include <propkey.h>
#include <tlhelp32.h>
#include <appmodel.h>
#include <winternl.h>
#include <psapi.h>